<?php

$apiKey= "rzp_test_mP2ySbsgw9aU5f";

?>

<form action="welcome.html" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['totalAmount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID' .rand(10,000).'END' ;?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Chef2Door"
    data-description="Chef2Door"
    data-image="https://thumbs.dreamstime.com/b/food-delivery-logo-design-fast-service-sign-online-ordering-restaurant-chief-197626291.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-theme.color="#F37254"

    jQuery.ajax({success:function(result){
        window.location.href="welcome.html";}});
                
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>